/* icons.js — The Secret Society demo · inline icon sprite.
   32 glyphs from lucide-static v1.48.0 (ISC License, Copyright (c) Lucide Contributors —
   https://lucide.dev/license) plus two glyphs drawn in the same 24-grid grammar (sliders, zap-square;
   DESIGN_TOKENS.md §10). Generated by scratchpad/measure/styletile/gen_icons.py — do not hand-edit the Lucide paths.
   `sliders` was redrawn in fix round 3 to the 6.5.3 Filters glyph: rings r 2.1 (outer ⌀ 4.6 CSS at the 17 box)
   left / right / left, lines 8 / 8 / 7.4 units, rows 7.2 apart — ink 13.0×14.8 CSS vs the measured 13.0×14.6.

   window.TSS_ICONS            { name: '<svg viewBox="0 0 24 24" …>…</svg>' }   (no width/height attrs)
   window.tssIcon(name, size, stroke)
       size   → width/height in CSS px (default 24)
       stroke → undefined = var(--icon-stroke) · 'bold' | 'heavy' | 'back' | 'badge' → var(--icon-stroke-<x>)
                · a number = literal CSS px · any other string is used verbatim (e.g. 'var(--x)')
       Every path carries vector-effect="non-scaling-stroke", so the stroke is CSS px at any box size.
   window.tssStatusBar(time)   inner HTML of a fake iOS status bar (time + signal/wifi/battery glyphs).
   window.tssMountIcons(root)  replaces <i data-icon="bell" data-size="26" data-stroke="bold"></i> placeholders
                               and fills [data-statusbar] elements; runs once on DOMContentLoaded.
   No network dependency. */
(function () {
  'use strict';

  var OPEN = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';

  var BODY = {
    "arrow-down-wide-narrow": "<path vector-effect=\"non-scaling-stroke\" d=\"m3 16 4 4 4-4\"/><path vector-effect=\"non-scaling-stroke\" d=\"M7 20V4\"/><path vector-effect=\"non-scaling-stroke\" d=\"M11 4h10\"/><path vector-effect=\"non-scaling-stroke\" d=\"M11 8h7\"/><path vector-effect=\"non-scaling-stroke\" d=\"M11 12h4\"/>",
    "arrow-left": "<path vector-effect=\"non-scaling-stroke\" d=\"m12 19-7-7 7-7\"/><path vector-effect=\"non-scaling-stroke\" d=\"M19 12H5\"/>",
    "arrow-up-right": "<path vector-effect=\"non-scaling-stroke\" d=\"M7 7h10v10\"/><path vector-effect=\"non-scaling-stroke\" d=\"M7 17 17 7\"/>",
    "bell": "<path vector-effect=\"non-scaling-stroke\" d=\"M10.268 21a2 2 0 0 0 3.464 0\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326\"/>",
    "briefcase": "<path vector-effect=\"non-scaling-stroke\" d=\"M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16\"/><rect vector-effect=\"non-scaling-stroke\" width=\"20\" height=\"14\" x=\"2\" y=\"6\" rx=\"2\"/>",
    "calendar": "<path vector-effect=\"non-scaling-stroke\" d=\"M8 2v3\"/><path vector-effect=\"non-scaling-stroke\" d=\"M16 2v3\"/><rect vector-effect=\"non-scaling-stroke\" x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3 9h18\"/>",
    "calendar-check": "<path vector-effect=\"non-scaling-stroke\" d=\"M8 2v3\"/><path vector-effect=\"non-scaling-stroke\" d=\"M16 2v3\"/><rect vector-effect=\"non-scaling-stroke\" x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3 9h18\"/><path vector-effect=\"non-scaling-stroke\" d=\"m9 15 2 2 4-4\"/>",
    "camera": "<path vector-effect=\"non-scaling-stroke\" d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"13\" r=\"3\"/>",
    "check": "<path vector-effect=\"non-scaling-stroke\" d=\"M20 6 9 17l-5-5\"/>",
    "chevron-down": "<path vector-effect=\"non-scaling-stroke\" d=\"m6 9 6 6 6-6\"/>",
    "chevron-right": "<path vector-effect=\"non-scaling-stroke\" d=\"m9 18 6-6-6-6\"/>",
    "clock": "<circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"12\" r=\"10\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 6v6l4 2\"/>",
    "heart": "<path vector-effect=\"non-scaling-stroke\" d=\"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5\"/>",
    "inbox": "<polyline vector-effect=\"non-scaling-stroke\" points=\"22 12 16 12 14 15 10 15 8 12 2 12\"/><path vector-effect=\"non-scaling-stroke\" d=\"M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z\"/>",
    "layout-grid": "<rect vector-effect=\"non-scaling-stroke\" width=\"7\" height=\"7\" x=\"3\" y=\"3\" rx=\"1\"/><rect vector-effect=\"non-scaling-stroke\" width=\"7\" height=\"7\" x=\"14\" y=\"3\" rx=\"1\"/><rect vector-effect=\"non-scaling-stroke\" width=\"7\" height=\"7\" x=\"14\" y=\"14\" rx=\"1\"/><rect vector-effect=\"non-scaling-stroke\" width=\"7\" height=\"7\" x=\"3\" y=\"14\" rx=\"1\"/>",
    "log-out": "<path vector-effect=\"non-scaling-stroke\" d=\"m16 17 5-5-5-5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M21 12H9\"/><path vector-effect=\"non-scaling-stroke\" d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\"/>",
    "map-pin": "<path vector-effect=\"non-scaling-stroke\" d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"10\" r=\"3\"/>",
    "menu": "<path vector-effect=\"non-scaling-stroke\" d=\"M4 5h16\"/><path vector-effect=\"non-scaling-stroke\" d=\"M4 12h16\"/><path vector-effect=\"non-scaling-stroke\" d=\"M4 19h16\"/>",
    "minus": "<path vector-effect=\"non-scaling-stroke\" d=\"M5 12h14\"/>",
    "pencil": "<path vector-effect=\"non-scaling-stroke\" d=\"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z\"/><path vector-effect=\"non-scaling-stroke\" d=\"m15 5 4 4\"/>",
    "plus": "<path vector-effect=\"non-scaling-stroke\" d=\"M5 12h14\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 5v14\"/>",
    "qr-code": "<rect vector-effect=\"non-scaling-stroke\" width=\"5\" height=\"5\" x=\"3\" y=\"3\" rx=\"1\"/><rect vector-effect=\"non-scaling-stroke\" width=\"5\" height=\"5\" x=\"16\" y=\"3\" rx=\"1\"/><rect vector-effect=\"non-scaling-stroke\" width=\"5\" height=\"5\" x=\"3\" y=\"16\" rx=\"1\"/><path vector-effect=\"non-scaling-stroke\" d=\"M21 16h-3a2 2 0 0 0-2 2v3\"/><path vector-effect=\"non-scaling-stroke\" d=\"M21 21v.01\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 7v3a2 2 0 0 1-2 2H7\"/><path vector-effect=\"non-scaling-stroke\" d=\"M3 12h.01\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 3h.01\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 16v.01\"/><path vector-effect=\"non-scaling-stroke\" d=\"M16 12h1\"/><path vector-effect=\"non-scaling-stroke\" d=\"M21 12v.01\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 21v-1\"/>",
    "refresh-cw": "<path vector-effect=\"non-scaling-stroke\" d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M21 3v5h-5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\"/><path vector-effect=\"non-scaling-stroke\" d=\"M8 16H3v5\"/>",
    "search": "<path vector-effect=\"non-scaling-stroke\" d=\"m21 21-4.34-4.34\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"11\" cy=\"11\" r=\"8\"/>",
    "server": "<rect vector-effect=\"non-scaling-stroke\" width=\"20\" height=\"8\" x=\"2\" y=\"2\" rx=\"2\" ry=\"2\"/><rect vector-effect=\"non-scaling-stroke\" width=\"20\" height=\"8\" x=\"2\" y=\"14\" rx=\"2\" ry=\"2\"/><line vector-effect=\"non-scaling-stroke\" x1=\"6\" x2=\"6.01\" y1=\"6\" y2=\"6\"/><line vector-effect=\"non-scaling-stroke\" x1=\"6\" x2=\"6.01\" y1=\"18\" y2=\"18\"/>",
    "sliders": "<circle vector-effect=\"non-scaling-stroke\" cx=\"6\" cy=\"4.8\" r=\"2.1\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12 4.8h8\"/><path vector-effect=\"non-scaling-stroke\" d=\"M4 12h8\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"18\" cy=\"12\" r=\"2.1\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"6\" cy=\"19.2\" r=\"2.1\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12.6 19.2h7.4\"/>",
    "star": "<path vector-effect=\"non-scaling-stroke\" d=\"M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z\"/>",
    "ticket": "<path vector-effect=\"non-scaling-stroke\" d=\"M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z\"/><path vector-effect=\"non-scaling-stroke\" d=\"M13 5v2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M13 17v2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M13 11v2\"/>",
    "user-round": "<circle vector-effect=\"non-scaling-stroke\" cx=\"12\" cy=\"8\" r=\"5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M20 21a8 8 0 0 0-16 0\"/>",
    "users": "<path vector-effect=\"non-scaling-stroke\" d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\"/><path vector-effect=\"non-scaling-stroke\" d=\"M16 3.128a4 4 0 0 1 0 7.744\"/><path vector-effect=\"non-scaling-stroke\" d=\"M22 21v-2a4 4 0 0 0-3-3.87\"/><circle vector-effect=\"non-scaling-stroke\" cx=\"9\" cy=\"7\" r=\"4\"/>",
    "x": "<path vector-effect=\"non-scaling-stroke\" d=\"M18 6 6 18\"/><path vector-effect=\"non-scaling-stroke\" d=\"m6 6 12 12\"/>",
    "zap-square": "<rect vector-effect=\"non-scaling-stroke\" x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5\"/><path vector-effect=\"non-scaling-stroke\" d=\"M12.5 7.5 9.5 12.5h4l-2 4\"/>"
  };

  var ICONS = {};
  Object.keys(BODY).forEach(function (name) {
    ICONS[name] = OPEN + ' class="icon icon-' + name + '">' + BODY[name] + '</svg>';
  });

  var FALLBACK = OPEN + ' class="icon icon-missing"><circle cx="12" cy="12" r="9" stroke-dasharray="3 3" vector-effect="non-scaling-stroke"/></svg>';

  function strokeValue(stroke) {
    if (stroke === undefined || stroke === null || stroke === '') return 'var(--icon-stroke)';
    if (typeof stroke === 'number') return stroke + 'px';
    if (/^(bold|heavy|back|badge)$/.test(stroke)) return 'var(--icon-stroke-' + stroke + ')';
    if (/^[0-9.]+$/.test(stroke)) return stroke + 'px';
    return stroke;
  }

  function tssIcon(name, size, stroke) {
    var svg = ICONS[name];
    if (!svg) {
      if (window.console) console.warn('tssIcon: unknown icon "' + name + '"');
      svg = FALLBACK;
    }
    var s = parseFloat(size) || 24;
    return svg.replace('<svg ', '<svg width="' + s + '" height="' + s + '" style="stroke-width:' + strokeValue(stroke) + '" ');
  }

  /* iOS status-bar glyphs (system UI, filled with currentColor; not part of the icon set). */
  var STATUS = {
    signal: '<svg viewBox="0 0 18 12" width="18" height="12" aria-hidden="true"><rect x="0" y="7.5" width="3" height="4.5" rx="1"/><rect x="5" y="5.2" width="3" height="6.8" rx="1"/><rect x="10" y="2.8" width="3" height="9.2" rx="1"/><rect x="15" y="0" width="3" height="12" rx="1"/></svg>',
    wifi: '<svg viewBox="0 0 17 12" width="17" height="12" aria-hidden="true"><path d="M8.5 2.55a9.6 9.6 0 0 1 6.85 2.85l-1.4 1.4A7.65 7.65 0 0 0 8.5 4.55a7.65 7.65 0 0 0-5.45 2.25l-1.4-1.4A9.6 9.6 0 0 1 8.5 2.55Z"/><path d="M8.5 6.05a6.1 6.1 0 0 1 4.35 1.8l-1.4 1.4a4.15 4.15 0 0 0-5.9 0l-1.4-1.4a6.1 6.1 0 0 1 4.35-1.8Z"/><path d="M8.5 9.55c.75 0 1.45.3 1.95.8L8.5 12.3l-1.95-1.95c.5-.5 1.2-.8 1.95-.8Z"/></svg>',
    battery: '<svg viewBox="0 0 28 13" width="28" height="13" aria-hidden="true"><rect x="0.6" y="0.6" width="23.8" height="11.8" rx="3.6" fill="none" stroke="currentColor" stroke-opacity="0.4" stroke-width="1.2"/><rect x="2.3" y="2.3" width="20.4" height="8.4" rx="2.2"/><path d="M25.7 4.55v3.9a1.95 1.95 0 0 0 0-3.9Z" fill-opacity="0.4"/></svg>'
  };

  function tssStatusBar(time) {
    return '<span class="statusbar-time">' + (time || '9:41') + '</span>' +
      '<span class="statusbar-icons">' + STATUS.signal + STATUS.wifi + STATUS.battery + '</span>';
  }

  function tssMountIcons(root) {
    root = root || document;
    var placeholders = root.querySelectorAll('[data-icon]');
    for (var i = 0; i < placeholders.length; i++) {
      var el = placeholders[i];
      if (el.tagName === 'svg') continue;
      var html = tssIcon(el.getAttribute('data-icon'), el.getAttribute('data-size') || 24, el.getAttribute('data-stroke'));
      var tpl = document.createElement('template');
      tpl.innerHTML = html;
      var node = tpl.content.firstElementChild;
      if (el.className) node.setAttribute('class', node.getAttribute('class') + ' ' + el.className);
      var label = el.getAttribute('aria-label');
      if (label) { node.setAttribute('role', 'img'); node.setAttribute('aria-label', label); node.removeAttribute('aria-hidden'); }
      el.parentNode.replaceChild(node, el);
    }
    var bars = root.querySelectorAll('[data-statusbar]');
    for (var j = 0; j < bars.length; j++) {
      bars[j].innerHTML = tssStatusBar(bars[j].getAttribute('data-statusbar'));
      bars[j].removeAttribute('data-statusbar');
    }
  }

  window.TSS_ICONS = ICONS;
  window.TSS_ICONS_VERSION = 'lucide-static 1.48.0';
  window.tssIcon = tssIcon;
  window.tssStatusBar = tssStatusBar;
  window.tssMountIcons = tssMountIcons;

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { tssMountIcons(document); });
  } else {
    tssMountIcons(document);
  }
})();
